name: Deploy to Remote Host

on:
  push:
    branches:
      - main  # Change to your main branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build Docker image
        run: |
            docker build -t my-express-app .
  
      - name: SCP Docker image to remote server
        run: |
            docker save my-express-app | bzip2 | ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'bunzip2 | docker load'
  
      - name: Run Docker container on remote server
        run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} \
            "docker stop my-express-app || true && docker rm my-express-app || true && \
             docker run -d -p 80:4000 --name my-express-app my-express-app"